import { productData } from "../types/productData";

export const products: productData[] = [
  {
    id: 1,
    image: "/image1.png",
    productName: "T-SHIRT WITH TAPE DETAILS",
    quality: "/quality4.5.png",
    price: 120,
    count: 1,
    categury: "simple",
  },
  {
    id: 2,
    image: "/image2.png",
    productName: "SKINNY FIT JEANS",
    quality: "/quality3.5.png",
    price: 240,
    count: 1,
    categury: "simple",
  },
  {
    id: 3,
    image: "/image3.png",
    productName: "CHECKERED SHIRT",
    quality: "/quality4.5.png",
    price: 180,
    count: 1,
    categury: "simple",
  },
  {
    id: 4,
    image: "/image4.png",
    productName: "SLEEVE STRIPED T-SHIRT",
    quality: "/quality4.5.png",
    price: 130,
    count: 1,
    categury: "simple",
  },
  {
    id: 5,
    image: "/image5.png",
    productName: "VERTICAL STRIPED SHIRT",
    quality: "/quality5.png",
    price: 216,
    count: 1,
    categury: "top_sell",
  },
  {
    id: 6,
    image: "/image6.png",
    productName: "COURAGE GRAPHIC T-SHIRT",
    quality: "/quality4.5.png",
    price: 145,
    count: 1,
    categury: "top_sell",
  },
  {
    id: 7,
    image: "/image7.png",
    productName: "LOOSE FIT BERMUDA SHORTS",
    quality: "/quality3.5.png",
    price: 80,
    count: 1,
    categury: "top_sell",
  },
  {
    id: 8,
    image: "/image8.png",
    productName: "FADED SKINNY JEANS",
    quality: "/quality4.5.png",
    price: 210,
    count: 1,
    categury: "top_sell",
  },
];
